image: Visual Studio 2019
artifacts:
  - path: '**\*.nupkg'

configuration:
  - Release

build_script:
  - cmd: >-
      dotnet build Trex.sln -p:Version=%APPVEYOR_BUILD_VERSION%

after_build:
  - cmd: >-
      dotnet pack .\t-rex\t-rex.csproj -c:release --no-build -p:Version=%APPVEYOR_BUILD_VERSION%

      dotnet pack .\TRexLib.nuget\TRexLib.nuget.csproj -c:release --no-build -p:Version=%APPVEYOR_BUILD_VERSION%

test_script:
  - cmd: >-
      dotnet test .\TRexLib.Tests\TRexLib.Tests.csproj