image: Visual Studio 2017
artifacts:
  - path: '**\t-rex*.nupkg'

configuration:
  - Release

build_script:
  - cmd: >-
      dotnet build Trex.sln -p:Version=%APPVEYOR_BUILD_VERSION%

after_build:
  - cmd: >-
      dotnet pack .\t-rex\t-rex.csproj -c:release --no-build -p:Version=%APPVEYOR_BUILD_VERSION%

test_script:
  - cmd: >-
      dotnet test .\TRexLib.Tests\TRexLib.Tests.csproj